[package]
name = "clash-tool"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.2"
reqwest = { version = "0.12.5", features = ["json", "rustls-tls", "cookies"] }
rustls = "0.23.12"
serde_json = "1.0.124"
tokio = { version = "1.39.2", features = ["full"] }
#home = "0.5.9"
serde = { version = "1.0.207", features = ["derive"] }
regex = "1.10.6"
fern = "0.6.2"
log = "0.4.22"
chrono = "0.4.38"
encoding_rs_io = "0.1.7"
scraper = "0.20.0"
clipboard = "0.5.0"
teloxide = "0.12.2"