[package]
name = "clash-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
reqwest = { version = "0.11.24", features = ["json"] }
serde_json = "1.0.111"
tokio = { version = "1.36.0", features = ["full"] }
home = "0.5.9"
serde = { version = "1.0.197", features = ["derive"] }
regex = "1.10.3"
env_logger = "0.11.2"