[package]
name = "clash-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
rustls = "0.22.2"
serde_json = "1.0.111"
tokio = { version = "1.36.0", features = ["full"] }
home = "0.5.9"
serde = { version = "1.0.197", features = ["derive"] }
regex = "1.10.3"
fern = "0.6"
log = "0.4.20"
chrono = "0.4.34"
