[package]
name = "clash-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
reqwest = { version = "0.11.24", features = ["json", "rustls-tls", "cookies"] }
rustls = "0.23.1"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
home = "0.5.9"
serde = { version = "1.0.197", features = ["derive"] }
regex = "1.10.3"
fern = "0.6.2"
log = "0.4.21"
chrono = "0.4.34"
encoding_rs_io = "0.1.7"
scraper = "0.19.0"
clipboard = "0.5.0"
enigo = "0.2.0-rc2"
teloxide = "0.12.2"